language: php
php:
  - 7.2
  - 7.3
  - 7.4

services:
  - docker

env:
  global:
    - APP_NAME=files_versions_s3
    - DB=sqlite
  matrix:
    - CORE_BRANCH=stable18

before_install:
  - cd ../
  - git clone https://github.com/nextcloud/server.git --recursive --depth 1 -b $CORE_BRANCH nextcloud
  - mv $APP_NAME nextcloud/apps/

install:
  - docker pull localstack/localstack
  - docker run -d -p 4569:4569 -e SERVICES=s3:4569 localstack/localstack
  - sleep 2
  - echo "<?php \$CONFIG=['objectstore' => ['class' => 'OC\Files\ObjectStore\S3','arguments' => ['bucket' => 'nextcloud','autocreate' => true,'key' => 'dummy','secret' => 'dummyj','hostname' => 'localhost','port' => 4569,'use_ssl' => false,'use_path_style'=>true]]];" > nextcloud/config/config.php
  - cat nextcloud/config/config.php

before_script:
  # fill nextcloud with default configs and enable the app
  - cd nextcloud
  - mkdir data
  - ./occ maintenance:install --database-name oc_autotest --database-user oc_autotest --admin-user admin --admin-pass admin --database $DB --database-pass=''
  - ./occ app:enable $APP_NAME
  - cd apps/$APP_NAME
  - composer install

script:
  # check syntax
  - vendor/bin/parallel-lint --exclude app --exclude vendor .
  # Run phpunit tests
  - cd tests
  - ../vendor/bin/phpunit --configuration phpunit.xml
